/// Dalin L 3.0 — WASM Code Generator
///
/// Compiles Dalin L AST directly to WebAssembly Text Format (WAT).
/// Structured control flow (if/while) maps directly to WASM blocks.
use dalin_compiler::ast::*;
use dalin_compiler::lexer::Lexer;
use dalin_compiler::parser::Parser;

pub struct WasmCodegen {
    wat: Vec<String>,
    indent: usize,
    /// Named local variables: name → WASM local index
    locals: std::collections::HashMap<String, u32>,
    next_local: u32,
    /// Function signatures for cross-references
    fns: Vec<(String, usize)>, // (name, param_count)
}

impl Default for WasmCodegen {
    fn default() -> Self {
        Self::new()
    }
}

impl WasmCodegen {
    pub fn new() -> Self {
        Self {
            wat: Vec::new(),
            indent: 0,
            locals: std::collections::HashMap::new(),
            next_local: 0,
            fns: Vec::new(),
        }
    }

    /// Compile Dalin L source to WAT text
    pub fn compile_source(&mut self, src: &str) -> Result<String, String> {
        let tokens = Lexer::new(src)
            .tokenize()
            .map_err(|e| format!("Lex error: {}", e))?;
        let mut parser = Parser::new(tokens);
        let prog = parser.parse();

        self.wat.clear();
        self.ln(";; Dalin L → WASM — Generated by dalin-codegen");
        self.ln("(module");
        self.indent();

        // Import: console-like print
        self.ln("(import \"env\" \"print\" (func $print (param i32)))");
        self.ln("(import \"env\" \"print_char\" (func $print_char (param i32)))");
        self.ln("");

        // Memory for strings and data
        self.ln("(memory (export \"memory\") 1)");
        self.ln("");

        // First pass: collect function signatures
        self.collect_fns(&prog);

        // Emit all functions
        for stmt in &prog.statements {
            if let Stmt::Fn { .. } = stmt {
                self.emit_function(stmt);
            }
        }

        // Emit data section for string constants
        // (simplified: strings stored as ASCII in memory starting at offset 0)

        self.dedent();
        self.ln(")");
        Ok(self.wat.join("\n"))
    }

    fn collect_fns(&mut self, prog: &Program) {
        for stmt in &prog.statements {
            if let Stmt::Fn { name, params, .. } = stmt {
                self.fns.push((name.clone(), params.len()));
            }
        }
    }

    fn emit_function(&mut self, stmt: &Stmt) {
        if let Stmt::Fn { name, params, body, .. } = stmt {
            self.locals.clear();
            self.next_local = 0;

            // Register parameters as locals
            let param_decls: Vec<String> = params.iter().enumerate()
                .map(|(i, p)| {
                    self.locals.insert(p.name.clone(), i as u32);
                    format!("(param ${} i32)", sanitize_name(&p.name))
                })
                .collect();

            self.ln(&format!(
                "(func ${} {} (result i32)",
                sanitize_name(name),
                param_decls.join(" ")
            ));
            self.indent();

            // Emit body
            for stmt in body {
                self.emit_stmt(stmt);
            }

            // Default return
            self.ln("i32.const 0");
            self.dedent();
            self.ln(")");
            self.ln("");
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { name, value, mutable: _, type_annotation: _ } => {
                // Allocate local slot
                let idx = self.next_local;
                self.locals.insert(name.clone(), idx);
                self.next_local += 1;
                self.ln(&format!("(local ${} i32)", sanitize_name(name)));

                if let Some(val) = value {
                    self.emit_expr(val);
                    self.ln(&format!("local.set ${}", sanitize_name(name)));
                }
            }
            Stmt::Fn { .. } => {
                // Functions are already emitted in the first pass
            }
            Stmt::Return(val) => {
                if let Some(expr) = val {
                    self.emit_expr(expr);
                    self.ln("return");
                } else {
                    self.ln("i32.const 0");
                    self.ln("return");
                }
            }
            Stmt::If { condition, then_body, else_body } => {
                self.emit_expr(condition);
                self.ln("if");
                self.indent();
                for s in then_body {
                    self.emit_stmt(s);
                }
                self.dedent();
                if !else_body.is_empty() {
                    self.ln("else");
                    self.indent();
                    for s in else_body {
                        self.emit_stmt(s);
                    }
                    self.dedent();
                }
                self.ln("end");
            }
            Stmt::While { condition, body } => {
                self.ln("block $exit");
                self.ln("loop $while");
                self.emit_expr(condition);
                self.ln("i32.eqz");
                self.ln("br_if $exit");
                for s in body {
                    self.emit_stmt(s);
                }
                self.ln("br $while");
                self.ln("end");
                self.ln("end");
            }
            Stmt::For { target, iterable, body } => {
                // Simplified for: iterate using index, assume array
                let idx = self.next_local;
                self.locals.insert(target.clone(), idx);
                self.next_local += 1;
                self.ln(&format!("(local ${} i32)", sanitize_name(target)));

                self.emit_expr(iterable);
                self.ln("local.set $__arr");

                // len would need array impl — simplified stub
                self.ln("i32.const 0");
                self.ln("local.set $__i");
                self.ln("block $exit_for");
                self.ln("loop $for_loop");
                // condition: __i < len
                self.ln("local.get $__i");
                self.ln("i32.const 100"); // max iteration bound
                self.ln("i32.ge_s");
                self.ln("br_if $exit_for");
                // Set target = __i
                self.ln("local.get $__i");
                self.ln(&format!("local.set ${}", sanitize_name(target)));
                for s in body {
                    self.emit_stmt(s);
                }
                self.ln("local.get $__i");
                self.ln("i32.const 1");
                self.ln("i32.add");
                self.ln("local.set $__i");
                self.ln("br $for_loop");
                self.ln("end");
                self.ln("end");
            }
            Stmt::Expr(expr) => {
                self.emit_expr(expr);
                self.ln("drop");
            }
            _ => {
                // Other declarations skipped in codegen
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::IntLiteral(val) => {
                self.ln(&format!("i32.const {}", val));
            }
            Expr::FloatLiteral(val) => {
                // Truncate float to i32 for WASM (simplified)
                self.ln(&format!("i32.const {}", *val as i64));
            }
            Expr::BoolLiteral(val) => {
                self.ln(&format!("i32.const {}", if *val { 1 } else { 0 }));
            }
            Expr::StringLiteral(_s) => {
                // String literal: store in memory at offset and push pointer
                // Simplified: push placeholder
                self.ln("i32.const 0");
            }
            Expr::CharLiteral(ch) => {
                self.ln(&format!("i32.const {}", *ch as i32));
            }
            Expr::Ident(name) => {
                if let Some(_idx) = self.locals.get(name) {
                    self.ln(&format!("local.get ${}", sanitize_name(name)));
                } else if let Some((fn_idx, _)) = self.fns.iter().position(|(n, _)| n == name).map(|i| (i, 0)) {
                    // Function reference — push its index
                    self.ln(&format!("i32.const {}", fn_idx));
                } else {
                    // Unknown identifier — push 0
                    self.ln("i32.const 0");
                }
            }
            Expr::BinaryOp { left, op, right } => {
                self.emit_expr(left);
                self.emit_expr(right);
                match op.as_str() {
                    "+" => self.ln("i32.add"),
                    "-" => self.ln("i32.sub"),
                    "*" => self.ln("i32.mul"),
                    "/" => self.ln("i32.div_s"),
                    "%" => self.ln("i32.rem_s"),
                    "==" => self.ln("i32.eq"),
                    "!=" => self.ln("i32.ne"),
                    "<"  => self.ln("i32.lt_s"),
                    ">"  => self.ln("i32.gt_s"),
                    "<=" => self.ln("i32.le_s"),
                    ">=" => self.ln("i32.ge_s"),
                    "&&" => self.ln("i32.and"),
                    "||" => self.ln("i32.or"),
                    _    => self.ln("i32.add"),
                }
            }
            Expr::UnaryOp { op, operand } => {
                self.emit_expr(operand);
                match op.as_str() {
                    "-" => {
                        self.ln("i32.const 0");
                        self.ln("i32.sub");
                    }
                    "!" => self.ln("i32.eqz"),
                    _   => {}
                }
            }
            Expr::Call { func, args } => {
                // Push arguments
                for arg in args {
                    self.emit_expr(arg);
                }
                if let Expr::Ident(name) = func.as_ref() {
                    // Check if it's a built-in or user function
                    match name.as_str() {
                        "print" | "println" => {
                            self.ln("call $print");
                            self.ln("i32.const 0"); // return value
                        }
                        _ => {
                            let fn_name = sanitize_name(name);
                            self.ln(&format!("call ${}", fn_name));
                        }
                    }
                } else {
                    self.ln("i32.const 0 ;; call stub");
                }
            }
            Expr::IfExpr(cond, then_expr, else_expr) => {
                self.emit_expr(cond);
                self.ln("if");
                self.indent();
                self.emit_expr(then_expr);
                self.dedent();
                self.ln("else");
                self.indent();
                self.emit_expr(else_expr);
                self.dedent();
                self.ln("end");
            }
            Expr::Array(items) => {
                // Array creation — simplified stub
                for item in items {
                    self.emit_expr(item);
                }
                self.ln("i32.const 0 ;; array stub");
            }
            Expr::Index { array, index } => {
                self.emit_expr(array);
                self.emit_expr(index);
                self.ln("i32.const 0 ;; index stub");
            }
            _ => {
                self.ln("i32.const 0");
            }
        }
    }

    fn ln(&mut self, s: &str) {
        let indent_str = "  ".repeat(self.indent);
        self.wat.push(format!("{}{}", indent_str, s));
    }

    fn indent(&mut self) { self.indent += 1; }
    fn dedent(&mut self) { if self.indent > 0 { self.indent -= 1; } }
}

fn sanitize_name(name: &str) -> String {
    if name.is_empty() { return "_empty".into(); }
    let first = name.chars().next().unwrap();
    if first.is_ascii_digit() {
        format!("_{}", name.replace(|c: char| !c.is_alphanumeric() && c != '_', "_"))
    } else {
        name.replace(|c: char| !c.is_alphanumeric() && c != '_', "_")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_function() {
        let mut cg = WasmCodegen::new();
        let result = cg.compile_source("fn add(a, b) -> int { return a + b }").unwrap();
        assert!(result.contains("func $add"), "WAT should contain 'func $add', got: {}", result);
        assert!(result.contains("i32.add"));
    }

    #[test]
    fn test_if_else() {
        let mut cg = WasmCodegen::new();
        let result = cg.compile_source("fn max(a, b) -> int { if a > b { return a } else { return b } }").unwrap();
        assert!(result.contains("if"));
        assert!(result.contains("else"));
    }

    #[test]
    fn test_while_loop() {
        let mut cg = WasmCodegen::new();
        let result = cg.compile_source("fn count(n) -> int { let i = 0 while i < n { i = i + 1 } return i }").unwrap();
        assert!(result.contains("loop"));
    }

    #[test]
    fn test_sanitize_name() {
        assert_eq!(sanitize_name("foo"), "foo");
        assert_eq!(sanitize_name("123abc"), "_123abc");
        assert_eq!(sanitize_name("my-func"), "my_func");
    }

    #[test]
    fn test_arithmetic() {
        let mut cg = WasmCodegen::new();
        let result = cg.compile_source("fn calc(x) -> int { return x * 2 + 1 }").unwrap();
        assert!(result.contains("i32.mul"));
        assert!(result.contains("i32.add"));
    }
}
