[package]
name = "dalin-runtime"
version.workspace = true
edition.workspace = true

[lib]
name = "dalin_runtime"
path = "src/lib.rs"

[dependencies]
dalin-compiler = { path = "../compiler" }
sha2 = "0.10"
rand = "0.8"

[[bench]]
name = "runtime_bench"
harness = false

[dev-dependencies]
criterion = "0.5"
