//! 高层 Agent API — 构建器模式 + 运行时封装

use crate::error::Result;
use crate::protocol::HandshakeProtocol;
use crate::transport::Transport;
use crate::types::{AgentId, Capability, Message, PeerInfo, Session, SessionId};

/// High-level Agent instance
///
/// Wraps the handshake protocol, transport layer, and session management, providing a concise Agent API.
///
/// ```rust,ignore
/// use dalin_handshake::prelude::*;
///
/// let mut agent = Agent::builder()
///     .name("my-agent")
///     .transport(Box::new(MemoryTransport::new("my-agent")))
///     .capability("compile", "3.0.0")
///     .build().unwrap();
///
/// agent.start().unwrap();
/// let _ = agent.discover().unwrap();
/// ```
pub struct Agent {
    /// 协议引擎
    protocol: HandshakeProtocol,
    /// 能力列表
    capabilities: Vec<Capability>,
    /// 是否已启动
    started: bool,
}

impl Agent {
    /// Create an Agent builder
    #[must_use]
    pub fn builder() -> AgentBuilder {
        AgentBuilder::new()
    }

    /// Start the Agent
    ///
    /// 1. Start the transport layer
    /// 2. Broadcast a discovery message
    /// 3. Start listening
    pub fn start(&mut self) -> Result<()> {
        self.protocol.start()?;
        self.started = true;
        Ok(())
    }

    /// Stop the Agent
    pub fn stop(&mut self) -> Result<()> {
        self.protocol.stop()?;
        self.started = false;
        Ok(())
    }

    /// Discover other Agents
    pub fn discover(&self) -> Result<Vec<PeerInfo>> {
        self.protocol.discover()
    }

    /// Initiate a handshake with the given peer
    pub fn handshake(&mut self, peer: &PeerInfo) -> Result<Session> {
        self.protocol.handshake(peer)
    }

    /// Send business data
    pub fn send(&self, session: &SessionId, payload: serde_json::Value) -> Result<()> {
        self.protocol.send_data(session, payload, None)
    }

    /// Receive a message (non-blocking)
    pub fn recv(&self) -> Result<Option<Message>> {
        self.protocol.recv()
    }

    /// Handle a received message
    pub fn handle(&mut self, msg: Message) -> Result<Option<Message>> {
        self.protocol.handle_message(msg)
    }

    /// Get this Agent's ID
    #[must_use]
    pub fn id(&self) -> &AgentId {
        self.protocol.agent_id()
    }

    /// Get the list of capabilities
    #[must_use]
    pub fn capabilities(&self) -> &[Capability] {
        &self.capabilities
    }

    /// Get active sessions
    #[must_use]
    pub fn sessions(&self) -> &std::collections::HashMap<SessionId, Session> {
        self.protocol.sessions()
    }

    /// Whether the Agent has been started
    #[must_use]
    pub fn is_started(&self) -> bool {
        self.started
    }
}

/// Agent builder
pub struct AgentBuilder {
    agent_id: Option<AgentId>,
    agent_name: Option<String>,
    agent_version: String,
    language: String,
    transport: Option<Box<dyn Transport>>,
    capabilities: Vec<Capability>,
    auth_token: Option<String>,
}

impl Default for AgentBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl AgentBuilder {
    #[must_use]
    pub fn new() -> Self {
        Self {
            agent_id: None,
            agent_name: None,
            agent_version: "1.0.0".to_string(),
            language: "rust".to_string(),
            transport: None,
            capabilities: Vec::new(),
            auth_token: None,
        }
    }

    /// Set the Agent ID (a UUID is auto-generated by default)
    #[must_use]
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.agent_id = Some(AgentId::new(id));
        self
    }

    /// Set the Agent name
    #[must_use]
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.agent_name = Some(name.into());
        self
    }

    /// Set the Agent version
    #[must_use]
    pub fn version(mut self, version: impl Into<String>) -> Self {
        self.agent_version = version.into();
        self
    }

    /// Set the language
    #[must_use]
    pub fn language(mut self, lang: impl Into<String>) -> Self {
        self.language = lang.into();
        self
    }

    /// Set the transport layer
    #[must_use]
    pub fn transport(mut self, transport: Box<dyn Transport>) -> Self {
        self.transport = Some(transport);
        self
    }

    /// Add a capability declaration
    #[must_use]
    pub fn capability(mut self, name: impl Into<String>, version: impl Into<String>) -> Self {
        self.capabilities.push(Capability::new(name, version));
        self
    }

    /// Set the authentication token
    #[must_use]
    pub fn auth(mut self, token: impl Into<String>) -> Self {
        self.auth_token = Some(token.into());
        self
    }

    /// Build the Agent instance
    pub fn build(self) -> Result<Agent> {
        let agent_id = self.agent_id.unwrap_or_else(AgentId::generate);
        let agent_name = self.agent_name.unwrap_or_else(|| "agent".to_string());
        let transport = self.transport.ok_or_else(|| {
            crate::error::HandshakeError::Protocol("Transport is required".to_string())
        })?;

        let mut protocol =
            HandshakeProtocol::new(agent_id, agent_name, &self.agent_version, transport);

        if let Some(token) = self.auth_token {
            protocol = protocol.with_auth(token);
        }

        protocol = protocol.with_language(&self.language);

        Ok(Agent {
            protocol,
            capabilities: self.capabilities,
            started: false,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transport::MemoryTransport;

    #[test]
    fn test_agent_builder() {
        let agent = Agent::builder()
            .name("test-agent")
            .version("1.0.0")
            .transport(Box::new(MemoryTransport::new("test-agent")))
            .capability("compile", "3.0.0")
            .capability("type_check", "3.0.0")
            .build()
            .expect("Should build agent");

        assert_eq!(agent.capabilities().len(), 2);
        assert!(!agent.is_started());
    }

    #[test]
    fn test_agent_lifecycle() {
        let mut agent = Agent::builder()
            .name("lifecycle-test")
            .transport(Box::new(MemoryTransport::new("lifecycle-test")))
            .build()
            .expect("Should build");

        assert!(!agent.is_started());
        agent.start().expect("Should start");
        assert!(agent.is_started());
        agent.stop().expect("Should stop");
        assert!(!agent.is_started());
    }

    #[test]
    fn test_agent_discover() {
        let mut agent = Agent::builder()
            .name("discover-test")
            .transport(Box::new(MemoryTransport::new("discover-test")))
            .build()
            .expect("Should build");

        agent.start().expect("Should start");
        let peers = agent.discover().expect("Should discover");
        // 没有其他 Agent，应该为空
        assert!(peers.is_empty());
    }
}
