[package]
name = "control-plane"
version.workspace = true
edition.workspace = true

[lib]
name = "control_plane"
path = "src/lib.rs"

[[bin]]
name = "cpd"
path = "bin/cpd.rs"

[dependencies]
dalin-compiler = { path = "../compiler" }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time"] }
tonic = "0.14"
prost = "0.14"
tonic-prost = "0.14"
async-nats = "0.50"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
uuid = { version = "1.0", features = ["v4"] }
futures-core = "0.3"
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["net", "sync"] }
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
etcd-client = "0.19"
tokio-postgres = "0.7"

[build-dependencies]
tonic-build = "0.14"
tonic-prost-build = "0.14"
